[build]
  publish = "dist"
  command = "npm run build"
  environment = { NODE_VERSION = "18" }

[[redirects]]
  from = "/privacy"
  to = "/integritetspolicy"
  status = 301

[[redirects]]
  from = "/terms"
  to = "/anvandarvillkor"
  status = 301

[[redirects]]
  from = "/manifest.webmanifest"
  to = "/manifest.json"
  status = 200

[[redirects]]
  from = "/apple-app-site-association"
  to = "/.well-known/apple-app-site-association"
  status = 200

[[redirects]]
  from = "/integritetspolicy"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/anvandarvillkor"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/om-oss"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Apple Store Compliant Headers for Security and Performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(self), payment=(self)"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Content-Security-Policy = "default-src 'self' https:; script-src 'self' 'unsafe-inline' https://www.bokadirekt.se; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https: blob:; frame-src 'self' https://www.bokadirekt.se; connect-src 'self' https: wss:; upgrade-insecure-requests"

# Apple Store Compliant Favicon Headers
[[headers]]
  for = "/Barberman Favicon/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "image/png"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/Barberman Favicon/favicon.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "image/x-icon"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/1024x1024.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "image/png"
    X-Apple-Store-Icon = "true"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Service-Worker-Allowed = "/"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/browserconfig.xml"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Content-Type = "application/xml"